### ISSUE TITLE
chef client parity vs blind load tester

### ISSUE THREAD

**Issue by jeremiahsnapp** [jeremiahsnapp/chef-load#12]
The error handling that was created by https://github.com/chef/chef-load/commit/f5da53d8906ec32655acb1c0bb4f61ef98bd8fe6 is designed to mostly simulate what a real chef client would do when it encounters an API error response. It causes that particular chef client run to fail gracefully which means no more API requests are made for that run.

Does this behavior represent what people expect from this load testing tool? Do we want chef-load to simulate as closely as possible the API behavior of a real chef client or do we want chef-load to blindly continue making all API requests for a particular chef client run and gracefully ignore any API error responses?

Along these lines I'd also like to hear what people think about adding the ability for chef-load to respond to 5xx API errors with retry logic similar to what the chef client does in the following code.

https://github.com/chef/chef/blob/master/lib/chef/http.rb#L397-L417

@irvingpop @itmustbejj @thomascate @danielsdeleo @ryancragun

**Comment by danielsdeleo** [comment]
Personally I want a blind load tester. At the conclusion of a chef-load run, I would love to have a report about the error rates and so on, but while it's running I'd rather have a steady load applied instead of the exponential backoff stuff that Chef Client does.

**Comment by jeremiahsnapp** [comment]
chef-load 3.0 should resolve this issue. Thanks for the input!
