### ISSUE TITLE
Regression:  chef-load 2.2.0 doesn't let you have empty/no chef_server_url

### ISSUE THREAD

**Issue by irvingpop** [jeremiahsnapp/chef-load#13]
Given the following config file:

```
data_collector_url = "http://myautomate/data-collector/v0/"
data_collector_token = "93a49a4f2482c64126f7b6015e6b0f30284287ee4054ff8807fb63d9cbd1c506"
```

chef-load 2.2.0 now complains:
```
ERROR: You must set client_name and client_key if chef_server_url is set
```

but this was a valid configuration under chef-load 2.1.0

**Comment by jeremiahsnapp** [comment]
@irvingpop sorry about that. I created that regression when I added this code.

https://github.com/chef/chef-load/blob/v2.2.0/config.go#L183-L185

I'll get a patch release out tomorrow to fix it.

**Comment by jeremiahsnapp** [comment]
chef-load 3.0 should resolve this issue. Thanks for reporting the bug!
