### ISSUE TITLE
useful to be able to simulate larger node object sizes

### ISSUE THREAD

**Issue by moutons** [jeremiahsnapp/chef-load#23]
some customers like to jam in unusual amounts of data into their node objects, and it might be handy to be able to use chef-load in a testing pipeline to simulate that, but it's definitely handy for us in support to be able to mock up a customer's environment including pushing a large object through the services to make sure we're not missing a tunable or something

**Comment by jeremiahsnapp** [comment]
Hi @moutons, chef-load is able to use ohai, converge-status and compliance-status JSON files to simulate customized data. Does that solve the issue for you?

https://github.com/chef/chef-load#using-sample-json-data-files

**Comment by moutons** [comment]
late answer, but yes it does!
