### ISSUE TITLE
(feature request) please include sample config file

### ISSUE THREAD

**Issue by vinyar** [jeremiahsnapp/chef-load#4]
- A sample config file
- Perhaps an output of knife acl to show what an admin client looks like from command line.

**Comment by smith** [comment]
This now exists.

**Comment by jeremiahsnapp** [comment]
You can generate a sample config file which includes inline documentation.

```
chef-load --sample-config > chef-load.conf
```

https://github.com/chef/chef-load#generate-a-chef-load-configuration-file
