### ISSUE TITLE
License

### ISSUE THREAD

**Issue by smith** [jeremiahsnapp/chef-load#8]
There's no LICENSE or COPYING file and nothing about a license in the README or any of the source files. This is one: https://spdx.org/licenses/Apache-2.0. Talk to your lawyer and get one.

**Comment by jeremiahsnapp** [comment]
Thanks a lot for pointing that out @smith. I added an Apache license and mentioned it in the README.

https://github.com/chef/chef-load/commit/b5f93a6c196c813fcf01853220845e248ccb9fdb
